### ISSUE TITLE
License install for TAC does not work

### ISSUE THREAD

**Issue by EdwardOst** [Talend/ansible-talend-platform#21]
Installing license to TAC does not seem to work.

The install.txt file is consumed by TAC on its first startup.  The format of install.txt file is very simple – it contains only 1 line (but with 200,000+ chars !)  So this line should be “license.key=<the content of license file>”.  But it appears not to work.

**Comment by EdwardOst** [comment]
Since install.txt is consumed on startup, it requires a reboot.  Also, I am not sure if it will work after the first startup.  Using metaservlet will allow for greater flexibility and even allow additional licenses to be added.

**Comment by iwangtalend** [comment]
This issue should now be resolved.
